# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Algolia < Formula
  desc "Algolia CLI utility"
  homepage "https://www.algolia.com"
  version "1.5.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/algolia/cli/releases/download/v1.5.0/algolia_1.5.0_macOS_arm64.tar.gz"
      sha256 "1e70029f94902cf1ee13619547050fcbbeea62c00c226367d88d793b206d2815"

      def install
        bin.install "algolia"
        bash_completion.install "completions/algolia.bash" => "algolia"
        zsh_completion.install "completions/algolia.zsh" => "_algolia"
        fish_completion.install "completions/algolia.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/algolia/cli/releases/download/v1.5.0/algolia_1.5.0_macOS_amd64.tar.gz"
      sha256 "d9ffec13ff250ce701ddf49a9b745ef332e6522d2f85dd67a2836f4b225d3d48"

      def install
        bin.install "algolia"
        bash_completion.install "completions/algolia.bash" => "algolia"
        zsh_completion.install "completions/algolia.zsh" => "_algolia"
        fish_completion.install "completions/algolia.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/algolia/cli/releases/download/v1.5.0/algolia_1.5.0_linux_armv6.tar.gz"
      sha256 "26b845713600d7a28b19b82287b52400a2c58ebc982b1da3e73534dc02212e5f"

      def install
        bin.install "algolia"
        bash_completion.install "completions/algolia.bash" => "algolia"
        zsh_completion.install "completions/algolia.zsh" => "_algolia"
        fish_completion.install "completions/algolia.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/algolia/cli/releases/download/v1.5.0/algolia_1.5.0_linux_arm64.tar.gz"
      sha256 "afd6630f2e398e3085fee5b9fa8f511b1cc49ad83ddf8ad5cfa3f21be16f0b31"

      def install
        bin.install "algolia"
        bash_completion.install "completions/algolia.bash" => "algolia"
        zsh_completion.install "completions/algolia.zsh" => "_algolia"
        fish_completion.install "completions/algolia.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/algolia/cli/releases/download/v1.5.0/algolia_1.5.0_linux_amd64.tar.gz"
      sha256 "47ade48b35347762e3c70aa0eb2c46087580f0648e45de515ff500661a19476c"

      def install
        bin.install "algolia"
        bash_completion.install "completions/algolia.bash" => "algolia"
        zsh_completion.install "completions/algolia.zsh" => "_algolia"
        fish_completion.install "completions/algolia.fish"
      end
    end
  end

  def caveats
    <<~EOS
      ❤ Thanks for installing the Algolia CLI!
    EOS
  end
end
